# Generated by Django 4.2.10 on 2024-02-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_url_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.TextField(),
        ),
    ]
